os:
  - Visual Studio 2019
  
platform: x64
  - x64
  
branches:
  only:
    - master

install:
  - git submodule update --init --recursive
  - set PATH=C:\Program Files\CMake\bin;%PATH%

build:
  verbosity: detailed

configuration:
  - Release
  - Debug
  
environment:
  artifactName: $(APPVEYOR_PROJECT_NAME)-$(APPVEYOR_REPO_COMMIT)-$(CONFIGURATION)
  matrix:
    - env_arch: "x64"
    - env_arch: "x86"
  
before_build:
  - mkdir build
  - cd build
  - if [%env_arch%]==[x64] (
    cmake .. -A x64 )
  - if [%env_arch%]==[x86] (
    cmake .. -A Win32 )
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=%APPVEYOR_BUILD_FOLDER%/%APPVEYOR_REPO_COMMIT% ..
  
build_script:
  - cmake --build . --config %CONFIGURATION% --target install
  
after_build:
  - mkdir %artifactName%
  - cp %APPVEYOR_BUILD_FOLDER%/%APPVEYOR_REPO_COMMIT%/*.* %artifactName%
  - if [%CONFIGURATION%]==[Debug] (
    cp -r %CONFIGURATION%/* %artifactName% )
  - if [%CONFIGURATION%]==[Debug] (
    cp -r pe-sieve/%CONFIGURATION%/* %artifactName% )
  
test_script:
  - ctest -V

artifacts:
  - path: build\%artifactName%
  
on_failure:
  - dir
  - 7z a about_failed.zip *
  - ps: Push-AppveyorArtifact about_failed.zip
  
